version: "3"
services:
  mysql-datasource:
    image: mysql:8
    container_name: mysql-datasource
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: AuthFlow
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  redis-cache:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass "Password@123"
#    networks:
#      - myungkeun-networks
#networks:
#  myungkeun-networks:
