version: "3"
services:
  mysql-datasource:
    image: mysql:8
    container_name: mysql-datasource
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: AuthFlow
      MYSQL_USER: user
      MYSQL_PASSWORD: password
#    networks:
#      - myungkeun-networks
#networks:
#  myungkeun-networks:
